forum_page:
    path: /forum
    defaults: { _controller: pgreca.pg_social.forum:handle }   
    
profile_page:
    path: social
    defaults: { _controller: pgreca.pg_social.controller:handle:index, name:mp, mode:profile }
    
status_page:
    path: status/{id}
    defaults: { _controller: pgreca.pg_social.controller:handle_status:index, id:0 }
    
pages_page:
    path: page/{name}
    defaults: { _controller: pgreca.pg_social.pages:handle:index, name:0 }