services:
    pgreca.pg_social.controller:
        class: pgreca\pg_social\controller\main
        arguments:
            - '@files.factory'
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '@pgreca.pg_social.helper'
            - '@pgreca.pg_social.notifyhelper'
            - '@pgreca.pg_social.social.post_status'
            - '@pgreca.pg_social.social.social_zebra'
            - '@pgreca.pg_social.social.social_chat'
            - '@pgreca.pg_social.social.social_photo'
            - '@pgreca.pg_social.social.social_tag'
            - '@pgreca.pg_social.social.social_page'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'   
            - '%core.table_prefix%' 
    pgreca.pg_social.pages:
        class: pgreca\pg_social\controller\pages
        arguments:
            - '@files.factory'
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '@pgreca.pg_social.helper'
            - '@pgreca.pg_social.notifyhelper'
            - '@pgreca.pg_social.social.post_status'
            - '@pgreca.pg_social.social.social_zebra'
            - '@pgreca.pg_social.social.social_photo'
            - '@pgreca.pg_social.social.social_tag'
            - '@pgreca.pg_social.social.social_page'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'   
            - '%core.table_prefix%'    
    pgreca.pg_social.helper:
        class: pgreca\pg_social\controller\helper
        arguments:
            - '@auth'
            - '@user'		
            - '@controller.helper'
            - '@pgreca.pg_social.notifyhelper'
            - '@config'
            - '@dbal.conn'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
    pgreca.pg_social.notifyhelper:
        class: pgreca\pg_social\controller\notifyhelper
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
    notification.type.social_status:
        class: pgreca\pg_social\notification\social_status
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pg_social.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }       
    notification.type.social_comments:
        class: pgreca\pg_social\notification\social_comments
        scope: prototype # scope MUST be prototype for this to work!
        arguments:           
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pg_social.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
    notification.type.social_likes:
        class: pgreca\pg_social\notification\social_likes
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pg_social.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
    notification.type.social_tag:
        class: pgreca\pg_social\notification\social_tag
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pg_social.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }   
    notification.type.social_zebra:
        class: pgreca\pg_social\notification\social_zebra
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pg_social.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }   
    pgreca.pg_social.social.post_status:
        class: pgreca\pg_social\social\post_status
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@pgreca.pg_social.helper'       
            - '@pgreca.pg_social.notifyhelper'     
            - '@pgreca.pg_social.social.social_photo'
            - '@pgreca.pg_social.social.social_tag'
            - '@pgreca.pg_social.social.social_zebra'
            - '@pgreca.pg_social.social.social_page'
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'        
    pgreca.pg_social.social.social_zebra:
        class: pgreca\pg_social\social\social_zebra
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@pgreca.pg_social.helper'
            - '@pgreca.pg_social.notifyhelper'
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'            
    pgreca.pg_social.social.social_photo:
        class: pgreca\pg_social\social\social_photo
        arguments:
            - '@template'
            - '@user'		
            - '@controller.helper'
            - '@pgreca.pg_social.helper'
            - '@pgreca.pg_social.social.social_tag'
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'  
    pgreca.pg_social.social.social_tag:
        class: pgreca\pg_social\social\social_tag
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@pgreca.pg_social.helper' 
            - '@pgreca.pg_social.social.social_zebra'
            - '@pgreca.pg_social.notifyhelper'  
            - '@config'
            - '@dbal.conn'
            - '%core.table_prefix%'       
    pgreca.pg_social.social.social_chat:
        class: pgreca\pg_social\social\social_chat
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@config'
            - '@dbal.conn'
            - '@pgreca.pg_social.helper'
            - '@pgreca.pg_social.social.social_zebra'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
    pgreca.pg_social.social.social_page:
        class: pgreca\pg_social\social\social_page
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@pgreca.pg_social.helper'       
            - '@pgreca.pg_social.notifyhelper'     
            - '@pgreca.pg_social.social.social_photo'
            - '@pgreca.pg_social.social.social_tag'
            - '@pgreca.pg_social.social.social_zebra'
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'  
    pgreca.pg_social.event.listener:
        class: pgreca\pg_social\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@auth'
            - '@request'
            - '@controller.helper'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@pgreca.pg_social.helper'
            - '@pgreca.pg_social.social.post_status'
            - '@pgreca.pg_social.social.social_photo'
            - '@pgreca.pg_social.social.social_zebra'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }